config/routes.rb
Laundry4::Application.routes.draw do
  get 'users/create'
  get 'users' => "users#index"
  get 'orders' => "users#index"
  get 'users/today' => "users#today"
  get 'users/month' => "users#month"
  get 'users/week' => "users#week"
  get 'orders/:id' => "users#show"
  get 'orders/:id/tab' => 'users#tab', as: :tab
  get 'orders/:id/sendmes' => "users#sendmes", as: :sendmes
  get 'orders/:id/sendmes_fin' => "users#sendmes_fin", as: :sendmes_fin
  match 'user_update_status/:id' => "users#update_status", as: :update_user, via: :put
  match 'orders/:id' => 'users#destroy', via: :delete
  match "user_new" => "users#new", via: :get
  match 'users/create' => "users#create", as: :create_user, via: :post
  resources :users
  resources :orders
  resources :item_temps
  resources :items

  root 'users#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_temps
  has_many :orders, through: :item_temps
end

app/models/item_temp.rb
class ItemTemp < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :item_temps
  has_many :items, through: :item_temps



  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  validates :name, :surname, presence: true
  validates :phone, length: { is: 10 }

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update_status, :sendmes, :tab, :sendmes_fin]
  before_action :set_hash, only: [:edit, :new, :index, :create, :update, :show, :today, :week, :month]
  before_action :hash_numbers, only: [:edit, :new, :index, :create, :update, :show, :today, :week, :month]
  
  def index
    @orders = Order.paginate(:page => params[:page], :per_page => 15)
    @orders_all = Order.all
    respond_to do |format|
      format.html
      format.xls
      format.xml  { render :xml => @orders_all }
    end
  end

  def show
  end
  
  def today
    @orders = Order.where(created_at: (Time.now.midnight)..Time.now.midnight + 1.day).paginate(:page => params[:page], :per_page => 15)
    respond_to do |format|
      format.html
      format.xls
      format.xml  { render :xml => @orders_all }
    end
  end

  def week
    @orders = Order.where(created_at: (Time.now.midnight)-7.days..Time.now.midnight + 1.day).paginate(:page => params[:page], :per_page => 15)

    respond_to do |format|
      format.html
      format.xls
      format.xml  { render :xml => @orders_all }
    end
  end

  def month
    @orders = Order.where(created_at: (Time.now.midnight)-1.month ..Time.now.midnight + 1.day).paginate(:page => params[:page], :per_page => 15)
    respond_to do |format|
      format.html
      format.xls
      format.xml  { render :xml => @orders_all }
    end
  end
  
  def tab
  end
  
  def new
    @user = User.new
    @order = Order.new
    @item_temp = ItemTemp.new
  end
  # POST /users
  # POST /users.json
  
  def create
    if User.find_by(phone: user_params["phone"]).nil?
      @user = User.new(user_params)
    else
      @user = User.find_by(phone: user_params["phone"])
    end
    @order = Order.new(order_params)
    @order.sum = 0
    params[:items].each do |key, value|
      @item_temp = ItemTemp.new(:item_id => value)
      @order.item_temps.push @item_temp
      if (@user.status) then
        @order.sum += Item.find(value).cost_student
      else
        @order.sum += Item.find(value).cost
      end
    end
    if (@user.status) then
      @order.sum += Item.find(1).cost_student * @order.zagr_stirka
      @order.sum += Item.find(2).cost_student * @order.zagr_sushka
    else
      @order.sum +=Item.find(1).cost * @order.zagr_stirka
      @order.sum += Item.find(2).cost * @order.zagr_sushka
    end

    @user.orders.push @order

    @user.save
    respond_to do |format|
      if @user.save
        format.html { redirect_to @order }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @order.destroy
    @order.item_temps.each do |f|
      f.destroy
    end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params) && @order.update(order_params) do
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      end
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_status
    @order.update(status: true)
    @order.save

    redirect_to(:action => :sendmes_fin)
  end

  def sendmes_fin
    message = MainsmsApi::Message.new(sender: 'sendertest', message: "Vash zakaz gotov. Mozhete zabirat`. Prachechnaya.", recipients: ['8'+@order.user.phone.to_s])
    response = message.deliver

    redirect_to(:action => :index)
  end

  def sendmes
    message = MainsmsApi::Message.new(sender: 'sendertest', :message => "TEXT", recipients: ['8'+@order.user.phone.to_s])
    response = message.deliver

    redirect_to(:action => :show)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @order = Order.find(params[:id])
    end
    def hash_numbers
      @users = User.all
      @phones = Array.new
      @users.each do |user|
        @phones.push user.phone
      end
      gon.phones = @phones
    end

    def set_hash
      @Item_hash = Hash.new()
      @Item_hash[:stirka] = Item.where(keyword: "stirka").to_a
      @Item_hash[:glazhka] = Item.where(keyword: "glazhka").to_a
      @Item_hash[:sushka] = Item.where(keyword: "sushka").to_a
      @Item_hash[:poroshok] = Item.where(keyword: "poroshok").to_a
      gon.sdf = @Item_hash.to_json
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require("user").permit("name", "surname", "phone", "status")
    end

    def order_params
      params.require("order").permit("user_id", "status", "other", "nal", "zagr_stirka", "zagr_sushka")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def items_count(id, order)
    i = 0
    order.items.each do |item|
      if item.id == id
        i += 1
      end
    end
    return i
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Laundry4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= javascript_include_tag :defaults %>
<div class="container">
  <% action_url = @user.new_record? ? users_create_url() : users_update_url(@user) %>
    
    <%= form_tag(action_url) do %>
      <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
      <% end %>
      <% if @order.errors.any? %>
        <% @order.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger"><%= msg %></div>
        <% end %>
      <% end %>
  
  <div id="main_cont">
    <div class="form-group" style="width: 400px;">
      <%= text_field_tag "user[name]", nil, :class => 'form-control', :placeholder => "Имя"%><br>
      <%= text_field_tag "user[surname]",nil, :class => 'form-control', :placeholder => "Фамилия"%>
    </div>
    <div class="input-group" style="width: 400px">
      <span class="input-group-addon">+7</span>
      <%= text_field_tag "user[phone]",nil, :class => 'form-control', :id => "autocomplete", :placeholder => "Телефон"%>
    </div><br>
      
    <div class="row" style="width: 600px">
      <div class="col-lg-6">
        <div class="input-group input-group-lg">
          <span class="input-group-addon">
            <%= check_box_tag "user[status]" %>
          </span>
          <input type="text" class="form-control" value='Пенсионер/студент' disabled>
        </div>
      </div>
    </div>

      <h4>Количество загрузок стирки:</h4>
      <div class="col-lg-6" style="width: 190px">
        <div class="input-group input-group-lg">
          <span class="input-group-btn">
            <button class="btn btn-default butt_minus" type="button">-</button>
          </span>
          <%=text_field_tag "order[zagr_stirka]", 0, :class => 'form-control'%>
          <span class="input-group-btn">
            <button class="btn btn-default butt_plus" type="button">+</button>
          </span>
        </div>
      </div>
  <br>
      <br><h4>Количество загрузок сушки:</h4>
      <div class="col-lg-6" style="width: 190px">
        <div class="input-group input-group-lg">
          <span class="input-group-btn">
            <button class="btn btn-default butt_minus" type="button">-</button>
          </span>
          <%=text_field_tag "order[zagr_sushka]", 0, :class => 'form-control'%>
          <span class="input-group-btn">
            <button class="btn btn-default butt_plus" type="button">+</button>
          </span>
        </div>
      </div><p><br><br><br>
      <h4>Заказы:</h4>
      
      <%= render partial: "accordion" %>


      <br><%= text_area_tag "order[other]",nil, :class => "form-control", :placeholder => "Комментарии", :style => "width: 400px", :rows =>'3' %><br><br>
      <div id = "orders">
      </div>

    <div class="row" style="width: 500px">
      <div class="col-lg-6">
        <div class="input-group input-group-lg">
          <span class="input-group-addon">
            <%= check_box_tag "order[nal]" %>
          </span>
          <input type="text" class="form-control" value='Наличные' disabled>
        </div>
      </div>
    </div><br>
      <%= submit_tag "Готово", :class => "btn btn-success" %>
      <%= link_to 'Назад', users_path, :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render partial: "form", object: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
<div class="page-header"><h1>Список заказов</h1></div>
<%= link_to 'Показать заказы за сегодня', users_today_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за неделю', users_week_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за месяц', users_month_path, :class => "btn btn-default" %>
<div style = "float:right; margin-right: 5%;"><button type="button" class="btn btn-info" onclick="status_hide()">Показать не готовые</button>
<button type="button" class="btn btn-primary" onclick="status_show()">Показать готовые</button></div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Телефон</th>
      <th>Статус</th>
      <th>Сумма</th>
      <th>Оплата</th>
      <th>Готовность</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.user.name %></td>
          <td><%= order.user.surname %></td>
          <td>+7<%= order.user.phone %></td>
          <% if (order.user.status) then %>
            <td>Студент/пенсионер</td>
          <% else %>
            <td>Без льгот</td>
          <% end %>
          <td><%= order.sum %> рублей</td>
          <% if order.nal then %>
            <td><i>оплата наличными</i></td>
          <% else %>
            <td><i>безналичная оплата</i></td>
          <% end %>
          <td><% if order.status %>
            <div class="btn-group-sm"><button class="btn btn-default status_finish" disabled>Заказ готов</button></div>
          <% else %>
            <div class="btn-group-sm"><%= link_to 'Готово', update_user_path(order.id), method: :put, :class => "btn btn-success status_not" %></td></div>
          <% end %>
          <td><%= link_to 'Показать заказ', order %></td>
          <td><%= link_to 'Удалить заказ', order, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<br>
<div style="float:right; margin-right: 10%"><%= will_paginate @orders, :previous_label => "Назад", :next_label => "Вперед", :class => "pagination pagination-sm" %></div>
<%= link_to 'Новый заказ', new_user_path, :class => 'btn btn-success' %>
<%= link_to "Перевести в Excel", users_path(:format => "xls"), :class => "btn btn-default" %>
</div>

app/views/users/index_today.html.erb
<div class="page-header"><h1>Список заказов</h1></div>
<%= link_to 'Показать все заказы', users_path, :class => "btn btn-default" %>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Телефон</th>
      <th>Статус</th>
      <th>Готовность</th>
      <th>Сумма</th>
      <th>Дата заказа</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <div class="man">
        <tr>
        <%if order.created_at.to_date==Date.current then %>
          <td><%= order.user.name %></td>
          <td><%= order.user.surname %></td>
          <td>+7<%= order.user.phone %></td>
          <% if (order.user.status) then %>
          <td>Студент/пенсионер</td>
          <% else %>
          <td>Без льгот</td>
          <% end %>
          <%if order.status  then%>
            <td>Заказ готов</td>
          <% else %>
            <td>Заказ не готов</td>
          <% end %>
          <td><%= order.sum %> рублей</td>
          <td><%= link_to 'Показать заказ', order.user %></td>
          <td><%= link_to 'Удалить заказ', order.user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      </div>
      <% end %>
      <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Новый заказ', new_user_path, :class => 'btn btn-success' %>

app/views/users/month.html.erb
<div class="container">
<div class="page-header"><h1>Список заказов</h1></div>
<%= link_to 'Показать все заказы', users_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за сегодня', users_today_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за неделю', users_week_path, :class => "btn btn-default" %>
<div style = "float:right; margin-right: 5%;"><button type="button" class="btn btn-info" onclick="status_hide()">Показать не готовые</button>
<button type="button" class="btn btn-primary" onclick="status_show()">Показать готовые</button></div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Телефон</th>
      <th>Статус</th>
      <th>Сумма</th>
      <th>Оплата</th>
      <th>Готовность</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.user.name %></td>
          <td><%= order.user.surname %></td>
          <td>+7<%= order.user.phone %></td>
          <% if (order.user.status) then %>
            <td>Студент/пенсионер</td>
          <% else %>
            <td>Без льгот</td>
          <% end %>
          <td><%= order.sum %> рублей</td>
          <% if order.nal then %>
            <td><i>оплата наличными</i></td>
          <% else %>
            <td><i>безналичная оплата</i></td>
          <% end %>
          <td><% if order.status %>
            <div class="btn-group-sm"><button class="btn btn-default status_finish" disabled>Заказ готов</button></div>
          <% else %>
            <div class="btn-group-sm"><%= link_to 'Готово', update_user_path(order.id), method: :put, :class => "btn btn-success status_not" %></td></div>
          <% end %>
          <td><%= link_to 'Показать заказ', order %></td>
          <td><%= link_to 'Удалить заказ', order, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<br>
<div style="float:right; margin-right: 10%"><%= will_paginate @orders, :previous_label => "Назад", :next_label => "Вперед", :class => "pagination pagination-sm" %></div>
<%= link_to 'Новый заказ', new_user_path, :class => 'btn btn-success' %>
<%= link_to "Перевести в Excel", users_path(:format => "xls"), :class => "btn btn-default" %>
</div>

app/views/users/new.html.erb
<div class="page-header"><h1>Новый заказ</h1></div>

<%= render partial: "form", object: @user %>

app/views/users/show.html.erb
<div class='container'><p id="notice"><%= notice %></p>

<p>
  <h4>Имя:</h4>
  <%= @order.user.name %>
</p>

<p>
  <h4>Фамилия:</h4>
  <%= @order.user.surname %>
</p>

<p>
  <h4>Телефон:</h4>
  +7 <%= @order.user.phone %>
</p>
<h4>Статус:</h4>
<% if @order.user.status then %>
  Пенсионер/студент
<% else %>
  Без льгот
<% end %>
<p>
  <h4>Комментарии:</h4>
  <%= @order.other %>
</p>
<p>
  <h4>Заказы:</h4>
  <% @order.items.each do |f| %>
  <i><%= f.name %>:</i>
  <% if @order.user.status then %>
  <b><%= f.cost_student %> рублей<br></b>
  <% else %>
  <b><%= f.cost %> рублей<br></b>
  <% end %>
  <% end %>
  <% if @order.user.status then %>
    <i><%= @order.zagr_stirka %> загрузок стирки:</i> <b><%= @order.zagr_stirka*Item.find(1).cost_student %> рублей</b><br>
    <i><%= @order.zagr_sushka %> загрузок сушки:</i> <b><%= @order.zagr_sushka*Item.find(2).cost_student %> рублей</b><br>
    <% else %>
     <%= @order.zagr_stirka %> загрузок стирки <%= @order.zagr_stirka*Item.find(1).cost %> рублей<br>
    <%= @order.zagr_sushka %> загрузок сушки <%= @order.zagr_sushka*Item.find(2).cost %> рублей<br>
  <% end %>
<p>  
<h5>Сумма:</h5>
  <%= @order.sum %> рублей, 
<% if @order.nal then %>
  <i><b>оплата наличными</b></i>
<% else %>
  <i><b>безналичная оплата</b></i>
<% end %>
</p>
<% if @order.status then %>
  <h4>Заказ готов</h4>
<% else %>
  <h4>Заказ не готов</h4>
<% end %>
<i>Количество заказов у этого человека:</i> <b><%= @order.user.orders.size %></b><br><br>
<%= link_to 'Готово', users_path, :class => 'btn btn-success' %>
<%= link_to "Сгенерировать чек", tab_path(@order.id), :class => 'btn btn-warning', :target => "_blank" %>
</div>

app/views/users/tab.html.erb
<div class="container">
<p><center><h2>КВИТАНЦИЯ</h2>
<h3>принято без осмотра и пересчета</h3></center></p>
<h4>№ <b><%= @order.id %></b>
 <div style="float:right"><%= @order.created_at.to_formatted_s(:db) %></div><br><br>
<center><i><%= @order.user.surname %> <%= @order.user.name %> 8<%= @order.user.phone %></i></center>
<hr style = "border-top: 1px solid black;">
<% if @order.user.status then %>
<center>
    <div class="col_left"><i>Стирка</i></div> <div class="col_center"><%= @order.zagr_stirka %>*<%= Item.find(1).cost_student %> <b><div class="col_right"><%= @order.zagr_stirka*Item.find(1).cost_student %> рублей</div></b></div><br>
    <i><div class="col_left">Сушка</div></i> <div class="col_center"><%= @order.zagr_sushka %>*<%= Item.find(2).cost_student %> <b><div class="col_right"><%= @order.zagr_sushka*Item.find(2).cost_student %> рублей</div></b></div><br>
    <% @hash = Hash.new() %>
    <% @order.items.each do |order| %>
      <% if @hash[order.id].nil? %>
        <% @hash[order.id] = 1 %>
      <% else %>
        <% @hash[order.id] += 1 %>
      <% end %>
    <% end %>
    <% @hash.each do |key, value| %>
      <i><div class="col_left"><%= Item.find(key).name %></div></i> <div class="col_center"><%= value %>*<%= Item.find(key).cost_student %> <b><div class="col_right"><%= Item.find(key).cost_student * value.to_i%> рублей</div></b></div><br>
    <% end %>
    </center>
    <% else %>
     <div class="col_block"><i><div class="col_left">Стирка</div></i> <div class="col_center"><%= @order.zagr_stirka %>*<%= Item.find(1).cost %> <b><div class="col_right"><%= @order.zagr_stirka*Item.find(1).cost %> рублей</div></b></div></div><br>
    <i><div class="col_left">Сушка</div></i> <div class="col_center"><%= @order.zagr_sushka %>*<%= Item.find(2).cost %> <div class="col_right"><b><%= @order.zagr_sushka*Item.find(2).cost %> рублей</b></div></div><br>
    <% @hash = Hash.new() %>
    <% @order.items.each do |order| %>
      <% if @hash[order.id].nil? %>
        <% @hash[order.id] = 1 %>
      <% else %>
        <% @hash[order.id] += 1 %>
      <% end %>
    <% end %>
    <% @hash.each do |key, value| %>
      <div class="col_left"><i><%= Item.find(key).name %></i></div><div class="col_center"><%= value %>*<%= Item.find(key).cost%><b><div class="col_right"><%= value*Item.find(key).cost %> рублей</div></b></div><br>
    <% end %>
    </center>
<% end %>
<hr style="border-top: 1px solid black;">
<div class="col_left">Итого</div> <div class="col_right"><strong><h4><%= @order.sum %> рублей</h4></strong></div><br><br>
Оплата: <% if @order.nal then %>
  <i><b>оплата наличными</b></i>
<% else %>
  <i><b>безналичная оплата</b></i>
<% end %>
</h4>
<center><h3>СОХРАНИТЕ</h3>
<h4>эту квитанцию для получения готового белья!</h4></center>
</div>

app/views/users/today.html.erb
<div class="container">
<div class="page-header"><h1>Список заказов</h1></div>
<%= link_to 'Показать все заказы', users_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за неделю', users_week_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за месяц', users_month_path, :class => "btn btn-default" %>
<div style = "float:right; margin-right: 5%;"><button type="button" class="btn btn-info" onclick="status_hide()">Показать не готовые</button>
<button type="button" class="btn btn-primary" onclick="status_show()">Показать готовые</button></div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Телефон</th>
      <th>Статус</th>
      <th>Сумма</th>
      <th>Оплата</th>
      <th>Готовность</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.user.name %></td>
          <td><%= order.user.surname %></td>
          <td>+7<%= order.user.phone %></td>
          <% if (order.user.status) then %>
            <td>Студент/пенсионер</td>
          <% else %>
            <td>Без льгот</td>
          <% end %>
          <td><%= order.sum %> рублей</td>
          <% if order.nal then %>
            <td><i>оплата наличными</i></td>
          <% else %>
            <td><i>безналичная оплата</i></td>
          <% end %>
          <td><% if order.status %>
            <div class="btn-group-sm"><button class="btn btn-default status_finish" disabled>Заказ готов</button></div>
          <% else %>
            <div class="btn-group-sm"><%= link_to 'Готово', update_user_path(order.id), method: :put, :class => "btn btn-success status_not" %></td></div>
          <% end %>
          <td><%= link_to 'Показать заказ', order %></td>
          <td><%= link_to 'Удалить заказ', order, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<br>
<div style="float:right; margin-right: 10%"><%= will_paginate @orders, :previous_label => "Назад", :next_label => "Вперед", :class => "pagination pagination-sm" %></div>
<%= link_to 'Новый заказ', new_user_path, :class => 'btn btn-success' %>
<%= link_to "Перевести в Excel", users_path(:format => "xls"), :class => "btn btn-default" %>
</div>

app/views/users/week.html.erb
<div class="container">
<div class="page-header"><h1>Список заказов</h1></div>
<%= link_to 'Показать все заказы', users_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за сегодня', users_today_path, :class => "btn btn-default" %>
<%= link_to 'Показать заказы за месяц', users_month_path, :class => "btn btn-default" %>
<div style = "float:right; margin-right: 5%;"><button type="button" class="btn btn-info" onclick="status_hide()">Показать не готовые</button>
<button type="button" class="btn btn-primary" onclick="status_show()">Показать готовые</button></div>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Телефон</th>
      <th>Статус</th>
      <th>Сумма</th>
      <th>Оплата</th>
      <th>Готовность</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <tr>
          <td><%= order.user.name %></td>
          <td><%= order.user.surname %></td>
          <td>+7<%= order.user.phone %></td>
          <% if (order.user.status) then %>
            <td>Студент/пенсионер</td>
          <% else %>
            <td>Без льгот</td>
          <% end %>
          <td><%= order.sum %> рублей</td>
          <% if order.nal then %>
            <td><i>оплата наличными</i></td>
          <% else %>
            <td><i>безналичная оплата</i></td>
          <% end %>
          <td><% if order.status %>
            <div class="btn-group-sm"><button class="btn btn-default status_finish" disabled>Заказ готов</button></div>
          <% else %>
            <div class="btn-group-sm"><%= link_to 'Готово', update_user_path(order.id), method: :put, :class => "btn btn-success status_not" %></td></div>
          <% end %>
          <td><%= link_to 'Показать заказ', order %></td>
          <td><%= link_to 'Удалить заказ', order, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>
<br>
<div style="float:right; margin-right: 10%"><%= will_paginate @orders, :previous_label => "Назад", :next_label => "Вперед", :class => "pagination pagination-sm" %></div>
<%= link_to 'Новый заказ', new_user_path, :class => 'btn btn-success' %>
<%= link_to "Перевести в Excel", users_path(:format => "xls"), :class => "btn btn-default" %>
</div>